### ISSUE TITLE
Build Failure for Windows

### ISSUE THREAD

**Issue by pcaversaccio** [HrikB/createXcrunch#1]
I tested the building process `cargo build --release` on Windows 11, Ubuntu, Debian & Kali Linux, and it all worked well except on Windows. If you build it with Windows, it currently throws with the following error:

```console
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\happy\\AppData\\Local\\Temp\\rustcYrfbvv\\symbols.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.0.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.1.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.2.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.3.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.4.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.4jdjvyu3knkdyy1a.rcgu.o" "/LIBPATH:C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps" "/LIBPATH:C:\\Users\\happy\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_msvc-0.52.0\\lib" "/LIBPATH:C:\\Users\\happy\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_msvc-0.48.5\\lib" "/LIBPATH:C:\\Program Files (x86)\\OCL_SDK_Light\\lib\\x86_64" "/LIBPATH:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcreatexcrunch-db5dd94951e67e4b.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libseparator-3954ea7d7b2f7aad.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl-258bbdfc1a896341.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnodrop-6fc1d686d771849c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libqutex-4aa811b02dc78004.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam-715476bb2d70005d.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_deque-49568b72147d3aaa.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_channel-51015bd5451d117e.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_queue-3968c78ba83f6b39.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_epoch-90a2d7b7f74d5a8c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_utils-d0f962c853191d40.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl_core-fa21dd4be04d1772.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libthiserror-a1204675e71711f8.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl_core_vector-93f5fd78b7bba75c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_complex-3559de3446d8d02c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcl_sys-81879bdbd346e6e0.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liblibc-3f018195b6a00961.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libenum_primitive-00adfcbc740427cb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_traits-e88b57ac5dca4677.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbitflags-d7289cf5651f6fc5.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_traits-c59946bc6e917bcb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libfutures-8b7107385ed9538c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libitertools-c03a9d87829ead5a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libeither-5ea1d1ab66c944fd.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libfs4-25e544b558561bbc.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libconsole-0c38eaabe3fbd5f7.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libencode_unicode-248d41002400a257.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libunicode_width-7a8e0c9a9d4d3a65.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liblazy_static-d85d8bd228e1d2a7.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbyteorder-79110348be754a9e.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liballoy_primitives-2e5ca44f6d8e198d.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libitoa-6670bc9b4600f250.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libhex_literal-248ceb1a0a1745ef.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libconst_hex-7db906d7aecc6d3a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcpufeatures-09032a232c256dd3.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbytes-60ea5d7a9fd1975c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libruint-967cf0419c8a5095.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand-c08ff7327340e490.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand_chacha-0336807059d79392.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libppv_lite86-a78377a92e12f19b.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand_core-eaf56b9a736d258f.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libgetrandom-bf7c470ae4ba02bb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcfg_if-54da7c9742ddd990.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libtiny_keccak-b8feea9451b43e0a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrunchy-f0aa7e6cb0b34419.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap-d03eda5d8c19f086.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap_builder-a9d8ef49bec3e19f.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libterminal_size-8f7e0f4b333629b1.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_sys-148008a0484355cd.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_targets-7a226fbd6adea308.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libstrsim-47935a4f5072e1ca.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstream-7637f9759ee28022.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_query-dc0ee170a2d7c8be.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_wincon-6619082b40b6a833.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_sys-2c8705c5238e6f74.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_targets-689f0c355e02f5fa.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcolorchoice-9cf6539c37109099.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_parse-70c07834aea22d76.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libutf8parse-34c1a0eefb559efe.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap_lex-02c755101ad28dc4.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle-1efee34d0a270a2d.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-d67e7b8bedb11cdc.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-64b1a07f55304d5e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-f120462e85f67653.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-d983e2a0a2a0c17a.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3ef2a86080fe9062.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-eb4d69e1a344b307.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-5d40568d59362563.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-23ecb7d440e7060a.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-d852afaab40eda7f.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-20556e3a8d3a4922.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-2ad8a2d023c9ae2e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-0731c9d2f2fdad4e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-8ed27bc4ebec64d5.rlib" "OpenCL.lib" "legacy_stdio_definitions.lib" "bcrypt.lib" "advapi32.lib" "windows.0.48.5.lib" "windows.0.52.0.lib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "ntdll.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: LINK : fatal error LNK1181: cannot open input file 'OpenCL.lib'
```

**Comment by Kay-79** [comment]
> I tested the building process `cargo build --release` on Windows 11, Ubuntu, Debian & Kali Linux, and it all worked well except on Windows. If you build it with Windows, it currently throws with the following error:
> 
> ```
> error: linking with `link.exe` failed: exit code: 1181
>   |
>   = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\happy\\AppData\\Local\\Temp\\rustcYrfbvv\\symbols.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.0.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.1.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.2.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.3.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.createxcrunch.9ee5a762c7a81365-cgu.4.rcgu.o" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.4jdjvyu3knkdyy1a.rcgu.o" "/LIBPATH:C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps" "/LIBPATH:C:\\Users\\happy\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_msvc-0.52.0\\lib" "/LIBPATH:C:\\Users\\happy\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\windows_x86_64_msvc-0.48.5\\lib" "/LIBPATH:C:\\Program Files (x86)\\OCL_SDK_Light\\lib\\x86_64" "/LIBPATH:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcreatexcrunch-db5dd94951e67e4b.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libseparator-3954ea7d7b2f7aad.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl-258bbdfc1a896341.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnodrop-6fc1d686d771849c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libqutex-4aa811b02dc78004.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam-715476bb2d70005d.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_deque-49568b72147d3aaa.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_channel-51015bd5451d117e.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_queue-3968c78ba83f6b39.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_epoch-90a2d7b7f74d5a8c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrossbeam_utils-d0f962c853191d40.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl_core-fa21dd4be04d1772.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libthiserror-a1204675e71711f8.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libocl_core_vector-93f5fd78b7bba75c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_complex-3559de3446d8d02c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcl_sys-81879bdbd346e6e0.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liblibc-3f018195b6a00961.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libenum_primitive-00adfcbc740427cb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_traits-e88b57ac5dca4677.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbitflags-d7289cf5651f6fc5.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libnum_traits-c59946bc6e917bcb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libfutures-8b7107385ed9538c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libitertools-c03a9d87829ead5a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libeither-5ea1d1ab66c944fd.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libfs4-25e544b558561bbc.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libconsole-0c38eaabe3fbd5f7.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libencode_unicode-248d41002400a257.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libunicode_width-7a8e0c9a9d4d3a65.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liblazy_static-d85d8bd228e1d2a7.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbyteorder-79110348be754a9e.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\liballoy_primitives-2e5ca44f6d8e198d.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libitoa-6670bc9b4600f250.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libhex_literal-248ceb1a0a1745ef.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libconst_hex-7db906d7aecc6d3a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcpufeatures-09032a232c256dd3.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libbytes-60ea5d7a9fd1975c.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libruint-967cf0419c8a5095.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand-c08ff7327340e490.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand_chacha-0336807059d79392.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libppv_lite86-a78377a92e12f19b.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\librand_core-eaf56b9a736d258f.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libgetrandom-bf7c470ae4ba02bb.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcfg_if-54da7c9742ddd990.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libtiny_keccak-b8feea9451b43e0a.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcrunchy-f0aa7e6cb0b34419.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap-d03eda5d8c19f086.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap_builder-a9d8ef49bec3e19f.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libterminal_size-8f7e0f4b333629b1.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_sys-148008a0484355cd.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_targets-7a226fbd6adea308.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libstrsim-47935a4f5072e1ca.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstream-7637f9759ee28022.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_query-dc0ee170a2d7c8be.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_wincon-6619082b40b6a833.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_sys-2c8705c5238e6f74.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libwindows_targets-689f0c355e02f5fa.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libcolorchoice-9cf6539c37109099.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle_parse-70c07834aea22d76.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libutf8parse-34c1a0eefb559efe.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libclap_lex-02c755101ad28dc4.rlib" "C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\libanstyle-1efee34d0a270a2d.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-d67e7b8bedb11cdc.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-64b1a07f55304d5e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-f120462e85f67653.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-d983e2a0a2a0c17a.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-3ef2a86080fe9062.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-eb4d69e1a344b307.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-5d40568d59362563.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-23ecb7d440e7060a.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-d852afaab40eda7f.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-20556e3a8d3a4922.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-2ad8a2d023c9ae2e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-0731c9d2f2fdad4e.rlib" "C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-8ed27bc4ebec64d5.rlib" "OpenCL.lib" "legacy_stdio_definitions.lib" "bcrypt.lib" "advapi32.lib" "windows.0.48.5.lib" "windows.0.52.0.lib" "kernel32.lib" "advapi32.lib" "bcrypt.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "kernel32.lib" "ws2_32.lib" "kernel32.lib" "ntdll.lib" "kernel32.lib" "msvcrt.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\Dev\\Blockchain\\createXcrunch\\target\\release\\deps\\createxcrunch.exe" "/OPT:REF,ICF" "/DEBUG" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\happy\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
>   = note: LINK : fatal error LNK1181: cannot open input file 'OpenCL.lib'
> ```

Solution: Install Nvidia CUDA toolkit --> restart --> remove Rust cache folder ```target```
It work for me!

**Comment by pcaversaccio** [comment]
> Solution: Install Nvidia CUDA toolkit --> restart --> remove Rust cache folder `target`

Right, I forgot about this issue :) - thanks for documenting.

**Comment by pde-rent** [comment]
Hi @pcaversaccio, thanks for your work here.
You should update the readme given that the windows build works well given the user has CUDA Toolkit installed or the Radeon equivalent. However the WSL2 installation fails on Windows x64 with Nvidia given that the driver does not yet support passing OpenCL to WSL1/2

**Comment by pcaversaccio** [comment]
> Hi @pcaversaccio, thanks for your work here. You should update the readme given that the windows build works well if the user has CUDA Toolkit installed or the Radeon equivalent. However the WSL2 installation fails on Windows x64 with Nvidia given that the driver does not yet support passing OpenCL to WSL1/2

Good point - are you ok with the wording here: https://github.com/HrikB/createXcrunch/pull/10?

**Comment by pde-rent** [comment]
> Good point - are you ok with the wording here: #10?

Great, sorry for the delay! (You got a new X follower, I'm @JakeTheSlug)
