### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by mds1** [HrikB/createXcrunch#3]
This issue aggregates things I've noticed:

- [x] 1. The repo should have some tests so we can confidently make changes and know that it still works. Currently I did not see any tests
- [x] 2. CLI argument improvements:
    - [x] 1. It panics if matching pattern is prefixed with 0x, and caller address is not prefixed with 0x. These are inconsistent, I'd suggest supporting both formats (0x prefix, or no 0x prefix)
    - [x] 2. It does not error on incorrect address checksums: should accept all lowercase addresses OR properly checksummed addresses. If there is a capital latter, validate checksum, and error if checksum is not valid.
- [x] 3. In terminal output, salts are prefixed with 0x, but addresses are not prefixed with 0x. I'd suggest prefixing both with 0x
    - One remaining missing 0x prefix in this part of output: `threshold: mining for Create3 address matching pattern 99999XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9`
- [x] 4. Terminal output gets mangled. Ideally, the output should start on the line below the command I entered, and continually add new  lines beneath, scrolling downwards. Instead it seems to start output way below, and scroll it upwards. In some terminals (like VSCode) this results in the command I entered being obfuscated. First pic shows the large output gap (warp terminal), second shows that the command I ran is not visible and instead you see the prior command I ran (VSCode integrated terminal)
    - iTerm2 output looks good, agreed we'll leave this one as-is since create2crunch behaves the same, and it seems something is nonstandard with VSCode and Warp terminals

<img width="1196" alt="image" src="https://github.com/HrikB/createXcrunch/assets/17163988/34005a95-ac9a-473e-b8b5-dde47b92febb">
<img width="1178" alt="image" src="https://github.com/HrikB/createXcrunch/assets/17163988/ae436a58-0352-4acc-8985-f69163856a79">

**Comment by HrikB** [comment]
Great thanks for all this feedback. Was definitely looking to get some testing added... just needed to think through exactly how to test the kernel.

Everything else sounds good. Will look to implement soon!

**Comment by mds1** [comment]
You probably could get away with just some e2e tests to make sure outputs are correct based on the inputs. Here’s how I did e2e testing of another rust binary if it helps https://github.com/ScopeLift/scopelint/blob/main/tests/check.rs

**Comment by pcaversaccio** [comment]
Looks like https://github.com/HrikB/createXcrunch/commit/4e9965f468798ed931f5ce3cdffca1151eabebff fixed the remaining issue about:
> missing 0x prefix in this part of `output: threshold: mining for Create3 address matching pattern 99999XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX9`

If @mds1 agrees, we can close this issue as completed.

**Comment by mds1** [comment]
Confirmed, thank you!
